services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
<<<<<<< HEAD
    image: golang:1.22
    command:
      - go
      - run
      - main.go
    volumes:
      - ./:/app
    working_dir: /app
=======
    build:
      context: .
      target: prod
>>>>>>> ba8d25e (Atualizando arquivos do projeto.)
    ports:
      - 8080:8080
    depends_on:
      - postgres
<<<<<<< HEAD
    environment:
      - DB_HOST=postgres
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=root
      - DB_PORT=5432
=======
>>>>>>> ba8d25e (Atualizando arquivos do projeto.)
